[package]
name = "dclx"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
serde = { version = "1.0.219", features = ["derive"] }
plotters = { version = "0.3.7", features = ["evcxr"] }
intx = "0.1.0"
num-traits = "0.2.19"
